version: "3.3"

services:
  auctios-db:
    image: mysql:5.6
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: 'auctionsdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'admin'
